### ISSUE TITLE
Is it possible to send data without bringing Obsidian to the foreground?

### ISSUE THREAD

**Issue by willasm** [Vinzent03/obsidian-advanced-uri#104] opened 2023-01-23 13:22 UTC
Not sure if it is possible but it would be nice if it I could send a text item to a note in Obsidian while working in another program and not have Obsidian activated as the foreground window. This would allow me to keep working in the application I'm currently using without having to alt-tab back to it every time.

**Comment by Vinzent03** [comment] 2023-01-23 13:35
Sorry, but that's not possible.
Duplicate of #25

**Closed** 2023-01-23 13:35 UTC
