### ISSUE TITLE
Open from URI Not Working

### ISSUE THREAD

**Issue by masorick** [Vinzent03/obsidian-advanced-uri#129] opened 2023-06-02 15:46 UTC
Clicking a link saved in an application other than Obsidian has stopped opening the target note.  Clicking the link switches to Obsidian but the note is not opened.  I've closed and reopened the Obsidian app.  I even deleted the plugin and then re-installed to no avail.

**Comment by Vinzent03** [comment] 2023-06-02 17:13
Please share your uri and check the console (CTRL + SHIFT + I) for any errors. Is there anything that has changed since it worked the last time?

**Comment by jorgb** [comment] 2023-06-02 18:33
I can confirm this being the case on Obsidian on Android as well, and Obsidian 1.3.5 on Windows.

To reproduce, I did:
- Obsidian URI : Copy URI for current file (to open)
- Select any other note but the one you want to open
- Paste note in link bar of your browser, let iit open
- It does not open the note, but the current note that was last opened

**Comment by masorick** [comment] 2023-06-02 19:46
> Please share your uri and check the console (CTRL + SHIFT + I) for any errors. Is there anything that has changed since it worked the last time?

obsidian://advanced-uri?vault=EgoNet&uid=08ba9bb6-52f3-4e6b-9d13-e2f32eddcc05

Received URL action 
Object
action
: 
"advanced-uri"
uid
: 
"08ba9bb6-52f3-4e6b-9d13-e2f32eddcc05"
vault
: 
"EgoNet"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()

**Comment by Vinzent03** [comment] 2023-06-02 20:18
Should be fixed now. Please try 1.36.1

**Comment by masorick** [comment] 2023-06-02 20:27
Issue resolved!  Thank you!

**Comment by Vinzent03** [comment] 2023-06-02 21:14
Thanks for your support!

**Closed by Vinzent03** 2023-06-02 21:14 UTC
